### PR TITLE
Update hub-default.bicep

### PR DESCRIPTION
**Pull request by costadelsolbjj**
Added a few Azure Government regions

I would like to add Azure Government regions to the region list to test the deployment in the  Azure Government

### CODE REVIEW

**Comment by costadelsolbjj** [comment]
I added only the following 3 regions for Azure   Government.
  'usgovvirginia'
  'usgovtexas'
  'usgovarizona'

**Comment by ckittel** [comment]
And was your test successful?

**Comment by ckittel** [comment]
If you want to keep this PR open, you'll need to have it catch up with some of the changes.  We're gong to be moving some bicep files around as well soon, so maybe refresh after that.  @costadelsolbjj

**Comment by ckittel** [comment]
Haven't seen any updates on this, closing.

**Pull request closed without merging**
